#!/bin/sh
uptime="`uptime -p | sed -e 's/up //g'`"

choice0=" Uptime: $uptime"
choice1="   Power Off"
choice2="   Restart"
choice3="   Lock"

chosen=$(printf "$choice0\n$choice1\n$choice2\n$choice3" | rofi -dmenu -i -no-show-icons -l 7 -width 30 -p " Power Options")


case "$chosen" in
  "$choice0") ;;
	"$choice1") poweroff ;;
	"$choice2") reboot ;;
	"$choice3") hyprlock ;;
esac

